version: "3.9"
services:
  develop:
    build:
      context: develop
      args:
        - R_VERSION=4.2.0
      dockerfile: Dockerfile.devenv
    command: /bin/sh -c "while sleep 1000; do :; done"
    container_name: tidymodels-dev
    volumes:
      # - user-data:/workspace
      - \\wsl.localhost\Ubuntu-20.04\workspace\tidymodels:/workspace
      # - /home/franz/.gnupg:/home/vscode/.gnupg:cached
      # - /var/run/docker.sock:/var/run/docker.sock:consistent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    # restart: unless-stopped
    # secrets:
    #   - db-password
    # expose:
    #   - 3306
    # ports:
    #   - 8080:80
volumes:
  user-data:
# secrets:
#   db-password:
#     file: develop/password.txt
